### ISSUE TITLE
Calculation of losses

### ISSUE THREAD

**Issue by lujunhao123** [WuQiangXDU/Peri-midFormer#1]
I noticed that in the training phase, the loss of label_len+pred_len is calculated and in the inference phase the pred_len is intercepted. why is this, have you taken the common approach please?

**Comment by QiangWu-AI** [comment]
Sorry for not getting back to you in a timely manner. It seems that you have solved the issue. Our approach references what many current methods do, i.e., by reconstructing part of the historical data (by means of label_len) during the training process to make the model better learn the essential properties of the data, which facilitates the prediction task. Thank you for your attention!
